package de.muenchen.reviewyou;

public enum QuestionCatalogue {
    GERMANLANGUAGE,
    ITKNOWLEDGE,
    INTERESTINWORK,
    ANALYTICALTHINKING,
    CONNECTEDTHINKING,
    WORKANDLEARNPRACTICES,
    COMMUNICATIONABILITY,
    CONTACABLITLITY,
    TEAMWORK,
    CONFLICTHANDLING,
    EMPATHY,
    RESPECTANDNOTRACIST,
    OPNENESS,
    INTEGRITY,
    MOTIVATION,
    STRESSTOLERANCE,
    IDENTIFICATION,
    SELFSUFFUCIENCY,
    CRITICALABILITY

}
